import type { ProductRecord } from "@/lib/api";

const seedTimestamp = "2026-01-01T00:00:00.000Z";

export const seedProducts: ProductRecord[] = [
  {
    id: "52d671be-c3f9-4f76-a673-c9f979f816d0",
    slug: "tiger-and-triumph",
    name: "Tiger and Triumph",
    price_inr: 2999,
    image_url: "/products/product-1.jpg",
    category: "Premium",
    product_type: "outfit",
    description: "A statement Indo-Western silhouette with sharp tailoring and celebratory energy.",
    is_featured: true,
    is_active: true,
    created_at: seedTimestamp,
    updated_at: seedTimestamp,
  },
  {
    id: "d36eec73-d7d8-4924-9d7b-3645e17a02e2",
    slug: "lotus-and-leather",
    name: "Lotus and Leather",
    price_inr: 15000,
    image_url: "/products/product-2.jpg",
    category: "Luxury",
    product_type: "outfit",
    description: "A bold fusion look that balances traditional detailing with a structured modern edge.",
    is_featured: true,
    is_active: true,
    created_at: seedTimestamp,
    updated_at: seedTimestamp,
  },
  {
    id: "d4efef1d-a07e-4814-bf66-4b4859f3d420",
    slug: "peacock-and-power",
    name: "Peacock and Power",
    price_inr: 12200,
    image_url: "/products/product-3.jpg",
    category: "Premium",
    product_type: "outfit",
    description: "Rich jewel tones and confident styling for festive evenings and standout occasions.",
    is_featured: false,
    is_active: true,
    created_at: seedTimestamp,
    updated_at: seedTimestamp,
  },
  {
    id: "50240380-7dd7-433f-8dc7-fb6409fb6d45",
    slug: "regal-fusion",
    name: "Regal Fusion",
    price_inr: 7599,
    image_url: "/products/product-4.jpg",
    category: "Classic",
    product_type: "outfit",
    description: "An elegant cross-cultural design with a refined ceremonial finish.",
    is_featured: false,
    is_active: true,
    created_at: seedTimestamp,
    updated_at: seedTimestamp,
  },
  {
    id: "a0a7e755-8b6b-4d26-b68f-7e537b3ca277",
    slug: "crimson-confluence",
    name: "Crimson Confluence",
    price_inr: 4500,
    image_url: "/products/product-5.jpg",
    category: "Luxury",
    product_type: "outfit",
    description: "A celebratory crimson ensemble created for intimate events and festive gatherings.",
    is_featured: false,
    is_active: true,
    created_at: seedTimestamp,
    updated_at: seedTimestamp,
  },
  {
    id: "af26d0ea-2d88-422d-bbc4-c1e7eaf0db64",
    slug: "ivory-valor",
    name: "Ivory Valor",
    price_inr: 4000,
    image_url: "/products/product-6.jpg",
    category: "Luxury",
    product_type: "outfit",
    description: "A clean ivory look with subtle heritage touches and understated luxury.",
    is_featured: false,
    is_active: true,
    created_at: seedTimestamp,
    updated_at: seedTimestamp,
  },
  {
    id: "f20a24ef-9e6b-434a-bb31-b9704c0f2865",
    slug: "the-royal-vision",
    name: "The Royal Vision",
    price_inr: 699,
    image_url: "/products/product-7.jpg",
    category: "Premium",
    product_type: "accessory",
    description: "A lightweight finishing accessory designed to elevate festive and cocktail looks.",
    is_featured: false,
    is_active: true,
    created_at: seedTimestamp,
    updated_at: seedTimestamp,
  },
  {
    id: "5ddf75b2-a08d-4147-a8c3-1cf5008d33ee",
    slug: "the-maharaja-knot",
    name: "The Maharaja Knot",
    price_inr: 2300,
    image_url: "/products/product-8.jpg",
    category: "Classic",
    product_type: "accessory",
    description: "A heritage-inspired accent piece with regal character and modern versatility.",
    is_featured: false,
    is_active: true,
    created_at: seedTimestamp,
    updated_at: seedTimestamp,
  },
  {
    id: "63ec2e9c-b5d5-43ce-8096-ce0f44445b5d",
    slug: "the-lotus-bind",
    name: "The Lotus Bind",
    price_inr: 5800,
    image_url: "/products/product-9.jpg",
    category: "Luxury",
    product_type: "accessory",
    description: "A premium handcrafted accessory with intricate styling for special occasions.",
    is_featured: true,
    is_active: true,
    created_at: seedTimestamp,
    updated_at: seedTimestamp,
  },
];
